//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavki
    {
        public DateTime StartDate { get; } = DateTime.Now;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postavki()
        {
            this.Jurnal_postavok = new HashSet<Jurnal_postavok>();
        }
    
        public int id { get; set; }
        public int id_postavshik { get; set; }
        public System.DateTime date_postavki { get; set; } = DateTime.Now.AddDays(5);
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jurnal_postavok> Jurnal_postavok { get; set; }
        public virtual postavshik postavshik { get; set; }
    }
}
