//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysMarket.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToysEntities : DbContext
    {
        public ToysEntities()
            : base("name=ToysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<brends> brends { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<Jurnal_postavok> Jurnal_postavok { get; set; }
        public virtual DbSet<jurnal_zakazovs> jurnal_zakazovs { get; set; }
        public virtual DbSet<postavki> postavki { get; set; }
        public virtual DbSet<postavshik> postavshik { get; set; }
        public virtual DbSet<prodaves> prodaves { get; set; }
        public virtual DbSet<toys> toys { get; set; }
        public virtual DbSet<ToysPhoto> ToysPhoto { get; set; }
        public virtual DbSet<type_toys> type_toys { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
    }
}
