//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToysMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zakaz()
        {
            this.jurnal_zakazovs = new HashSet<jurnal_zakazovs>();
        }
    
        public int id { get; set; }
        public string date_pokupki { get; set; }
        public Nullable<int> id_client { get; set; }
        public int id_prodaves { get; set; }
    
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jurnal_zakazovs> jurnal_zakazovs { get; set; }
        public virtual prodaves prodaves { get; set; }
    }
}
